# Generated by Django 4.2.28 on 2026-02-22 20:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('tenant', 'Locataire'), ('owner', 'Propriétaire')], default='tenant', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de Début')),
                ('date_fin', models.DateField(verbose_name='Date de Fin')),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du Loyer')),
                ('actif', models.BooleanField(default=True, verbose_name='Contrat Actif')),
                ('contrat_document', models.FileField(blank=True, null=True, upload_to='contrats_baux/', verbose_name='Contrat (Document)')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Baux',
            },
        ),
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Superficie (m²)')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('commercial', 'Local Commercial')], max_length=20, verbose_name='Type de Bien')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('maintenance', 'En Maintenance')], default='disponible', max_length=20, verbose_name='Statut')),
                ('loyer_estime', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Loyer Estimé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Bien Immobilier',
                'verbose_name_plural': 'Biens Immobiliers',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Payé')),
                ('date_paiement', models.DateField(auto_now_add=True, verbose_name='Date de Paiement')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement Bancaire'), ('carte', 'Carte Bancaire'), ('espece', 'Espèce'), ('cheque', 'Chèque')], max_length=20, verbose_name='Mode de Paiement')),
                ('recu_document', models.FileField(blank=True, null=True, upload_to='recus_paiements/', verbose_name='Reçu (Document)')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='immobilier.bail', verbose_name='Bail Associé')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='DemandeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('attente', 'En Attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='attente', max_length=20, verbose_name='Statut de la Demande')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la Demande')),
                ('documents_justificatifs', models.FileField(blank=True, null=True, upload_to='documents_demandes/', verbose_name='Documents Justificatifs')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='immobilier.bienimmobilier', verbose_name='Bien Immobilier')),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Demande de Location',
                'verbose_name_plural': 'Demandes de Location',
            },
        ),
        migrations.CreateModel(
            name='ChargeDepense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charge', models.CharField(choices=[('recurrente', 'Charge Récurrente'), ('exceptionnelle', 'Dépense Exceptionnelle (Réparation, etc.)')], max_length=20, verbose_name='Type de Charge')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_facturation', models.DateField(verbose_name='Date de Facturation')),
                ('document_facture', models.FileField(blank=True, null=True, upload_to='factures_charges/', verbose_name='Facture (Document)')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='immobilier.bienimmobilier', verbose_name='Bien Immobilier')),
            ],
            options={
                'verbose_name': 'Charge / Dépense',
                'verbose_name_plural': 'Charges et Dépenses',
            },
        ),
        migrations.AddField(
            model_name='bail',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baux', to='immobilier.bienimmobilier', verbose_name='Bien Immobilier'),
        ),
        migrations.AddField(
            model_name='bail',
            name='locataire',
            field=models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='baux', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
    ]
