# Generated by Django 4.2.28 on 2026-02-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_expediteur',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro Expéditeur'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('attente', 'En Attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('sedad', 'Sedad'), ('espece', 'Espèce'), ('virement', 'Virement Bancaire')], max_length=20, verbose_name='Mode de Paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
    ]
