# Generated by Django 6.0 on 2026-02-23 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_demandelocation_message_demandelocation_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelocation',
            name='candidat',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to=settings.AUTH_USER_MODEL, verbose_name='Candidat'),
        ),
    ]
